---
- name: package
  apt:
    name: nginx
    update_cache: yes

- name: disable default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: install config
  template:
    dest: /etc/nginx/sites-available/{{server_name}}
    src: nginx.conf.j2

- name: enable config
  file:
    dest: /etc/nginx/sites-enabled/{{server_name}}
    src: /etc/nginx/sites-available/{{server_name}}
    state: link
