---
- set_fact:
    this_release_path: "{{ releases_dir }}/{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
- debug:
    msg: "New release path {{ this_release_path }}"

- name: ensure all directories exist
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - "{{ work_dir }}"
    - "{{ repo_dir }}"
    - "{{ releases_dir }}"
    - "{{ this_release_path }}"

- name: clone repo
  git:
    repo: https://github.com/tank-bohr/reminder_bot.git
    dest: "{{ repo_dir }}"

- name: build
  shell: rebar3 release --output-dir {{ this_release_path }}
  args:
    chdir: "{{ repo_dir }}"

- name: symlink new release
  file:
    src: "{{ this_release_path }}"
    dest: "{{ releases_dir }}/current"
    state: link
    force: yes
    owner: "{{ user }}"
    group: "{{ user }}"

- name: cleanup the old releases
  shell: "ls -1t {{ releases_dir }} | tail -n +{{ keep_releases + 1 }} | xargs rm -rf"
  args:
    chdir: "{{ releases_dir }}"

- name: ensure systemd unit installed
  template:
    src: systemd-unit.service.j2
    dest: "/etc/systemd/system/{{ project_name }}.service"
  notify:
    - daemon reload

- name: Run
  systemd:
    name: "{{ project_name }}"
    state: restarted
